### ISSUE TITLE
Sample project 

### ISSUE THREAD

**Issue by yesidlazaro** [aashrey99/Sectioner#1]
it will be great if you show us a example.

**Comment by aashreys** [comment]
Yes, I am currently working on a sample. I do apologize for not including one from the get go. It should be up in a couple of days.

**Comment by yesidlazaro** [comment]
@aashrey99 thanks

**Comment by aashreys** [comment]
I've started work on the sample and have pushed an initial version [here](https://github.com/aashrey99/Sectioner/tree/feature_sample). The code is functional, however the sample should be considered pre-release at this point. I have yet to polish the UI and comment my code. I will be doing that soon.

**Comment by aashreys** [comment]
A sample is now available for reference.
